Add OPB module
bianjieai/irita pull request #88
Opened 2021-01-25 11:37 UTC by secret2830

Add OPB module

- [x] Proto
- [x] Types
- [x] Keeper
- [x] Handler
- [x] Genesis
- [x] Client
- [x] Msg tests

2021-01-26 02:28 UTC, chengwenxi requested changes

2021-01-26 02:28 UTC, chengwenxi commented on modules/opb/keeper/params.go
> +	)
```suggestion
	k.paramSubspace.GetParamSet(ctx, &params)
```

2021-01-26 02:28 UTC, chengwenxi commented on modules/opb/keeper/keeper.go
> +	return k.bankKeeper.SendCoins(ctx, moduleAccAddr, recipient, sdk.NewCoins(balance))
```suggestion
	return k.bankKeeper.SendCoinsFromModuleToAccount(ctx, types.PointTokenFeeCollectorName, recipient, sdk.NewCoins(balance))
```

2021-01-26 06:08 UTC, chengwenxi approved these changes

2021-03-08 10:26 UTC, dgsbl commented on cmd/irita/cmd/testnet.go
> +	var tokenGenState toketypes.GenesisState
tokentypes

2021-03-08 11:22 UTC, chengwenxi approved these changes

2021-03-08 11:24 UTC, merged